### ISSUE TITLE
Add pre-commit framework

### ISSUE THREAD

**Issue by keimlink** [transcode-de/cookiecutter-django-project#33]
Add the [pre-commit framework](http://pre-commit.com/) to the project to run checks before pushing commits.

**Comment by rm--** [comment]
There exists a [list of pre defined hooks](https://github.com/pre-commit/pre-commit-hooks#hooks-available) we can enable:

I tried the framework and that's my experience:
- `pre-commit` has to be enabled with `pre-commit install` after `git init`
- I would like to use as many hooks as possible
- I excluded the following hooks:
  - `pyflakes`  (because there is message: `Pyflakes (DEPRECATED, use flake8)`)
  - `detect-aws-credentials` because we don't use AWS yet
  - `detect-private-key` because we don't have something like in a repository ;)
  - `pretty-format-json` It can't be found in the pre-commit version I use
- `autopep8` don't accept my configuration (without config it corrected files like in the docs dir)
- `end-of-file-fixer` likes to correct all files (static files too, I see no way to exclude them)

So what do you think which hooks should be included/excluded and why?
Do you see a mistake in my configuration for `autopep8` and a way to exclude static files with `end-of-file-fixer`?

**Comment by keimlink** [comment]
From the pre-commit core hooks I would only use these four:
1. `debug-statements` - to prevent commits containing pdb
2. `flake8` - to run _always_ flake8 checks
3. `check-json` - Checking JSON syntax is a good idea, sometimes we have some JSON files
4. `check-case-conflict` - file name case conflicts do not happen very often, but if they happen fixing them is not funny

There are two other hooks that I think are very promising:
1. [pre-commit-python-sorter](https://github.com/FalconSocial/pre-commit-python-sorter) - relies on isort, which we already use
2. [pre-commit-mirrors-pep257](https://github.com/FalconSocial/pre-commit-mirrors-pep257) - we don't use pep257 yet, but it looks very promising

pre-commit-mirrors-pep257 is using [pep257](https://github.com/GreenSteam/pep257), but as a fixed (and outdated) dependency. So we could just install pep257 manually and add our own hook.

All the other hooks do not look very useful to me. We also have to keep in mind that running the hooks takes time and that we don't want to slow down the working speed.
